### ISSUE TITLE
Ping interval only affect 1 column

### ISSUE THREAD

**Issue by CreatoX** [R-Smith/vmPing#2]
Hi,

When changing the (global) Ping Interval time, let's say to 30 sec, only one ping is adjusted. 

![image](https://cloud.githubusercontent.com/assets/6085366/26403058/067f510e-408d-11e7-8b7f-9d7e28343141.png)

Is this adjustable per monitoring ping?

**Comment by R-Smith** [comment]
It looks like I did a fixed interval of 4 seconds for TCP port "pings".  When you adjust the global interval, it's only adjusting it for standard ICMP pings.

I'll tie the TCP port ping interval to the global interval setting so that it applies to both port pings and ICMP pings.

**Comment by R-Smith** [comment]
This is now fixed in v1.1.10.  The global probe interval is applied to both ICMP and TCP port pings.  However, TCP port pings still have a minimum interval of four seconds, but anything greater than that will be applied.

In a future release, there will be more configurable probe options for both ICMP and TCP as well as individual settings for each probe.
