### ISSUE TITLE
Portable mode

### ISSUE THREAD

**Issue by umbertoB67** [R-Smith/vmPing#28]
Hi Ryan,
vmPing is a really very useful tool.
Is it possible to add an option to make vmPing really portable writing vmPing.xml file in the same folder of the executable?
Best regards.

**Comment by nuno-andre** [comment]
This could be easily implemented by searching the xml in the current working directory and falling back to the user profile.

**Comment by R-Smith** [comment]
I always figured the application was portable, as there's no installer and does no registry reads/writes. If you choose to save a configuration of some kind, it writes to: %LocalAppData%\vmPing\vmPing.xml

So to be considered truly portable, the vmPing.xml file should stay with the .exe? Checking for and reading/writing vmPing.xml in the current directory is easy enough to implement. But what would the UX need to be like when no configuration exists and vmPing goes to create the xml file? I don't want it defaulting to the current directory.

**Comment by An-dir** [comment]
my idea. vmPing should search for vmPing.xml in current Directory or if started with "vmping.exe c:\temp\vmPing.xml" use that file instead of the one in appdata.

Add a option to convert the configuration to portable. That would work for everyone currently using vmPing.
![portable](https://user-images.githubusercontent.com/11379014/110180146-8c627400-7e09-11eb-94a0-e81fa08c59e4.png)

When you select the checkbox in options then you will be prompted to move or copy current file from appdata to the directory the exe resides in.
If the vmping already was started with a xml file the checkbox is already activated. if you then disable it you are prompted to move the configuration file back to appdata and overwrite eventually existing configuration there.  
so creation is always as it is now, but it can be converted. An empty Dummy XML file might also be an option to start with "portable-configuration-mode"

**Comment by R-Smith** [comment]
Support for reading/writing an existing config in the same directory as the .exe is now added here: f64f3d52f32a4b914171174029213a23146b2d03

That part will at least be in the next release.

**Comment by R-Smith** [comment]
Here's what I'm leaning towards:

![vmping-save](https://user-images.githubusercontent.com/22605441/110224532-5ff23a80-7e91-11eb-8537-9edaea40c8d5.png)

Since aliases and favorites use the same config file, the prompt would appear anytime you do something needing the config and the file doesn't already exist. Checking the portable mode box would update the displayed path to match.

**Comment by R-Smith** [comment]
Portable mode was added here: f64f3d52f32a4b914171174029213a23146b2d03 and here: c01d536f0d64da88272bad9891cf4a24ea33a26f

In addition to reading/writing vmping.xml if found in the current directory, you are now given a prompt the first time you save settings and no existing config file was found.

Included in release 1.3.14 out now.
