### ISSUE TITLE
1.3.8 - Detected by microsoft windows defender as Trojan:Win32/Tnega!ml

### ISSUE THREAD

**Issue by vtainc** [R-Smith/vmPing#54]
Trojan:Win32/Tnega!ml

**Comment by R-Smith** [comment]
Windows defender isn't flagging any of my vmPing executables on my system. I know you will get a Windows Defender SmartScreen warning when you first run the .exe, but that is because I haven't paid for a code signing cert and SmartScreen flags everything that's unsigned. If you open PowerShell, try Get-FileHash <path_to_vmping.exe> - Mine is showing ECBA43A378DAC6395EFAC726E0F74D6CDA20F1212C3E1E687885032A3DEA1CA1

**Comment by vtainc** [comment]
Yes, the hash is correct. But windows defender does like new file. This happened after latest update of windows defender database. I was succesfully using this app after update, but only today I found that I'm unable to start it, because defender started to block it.

PS C:\Users\VTA\Downloads> get-filehash .\vmPing.exe

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          ECBA43A378DAC6395EFAC726E0F74D6CDA20F1212C3E1E687885032A3DEA1CA1       C:\Users\VTA\Downloads\vmPing...


Antimalware Client Version: 4.18.2101.9
Engine Version: 1.1.17800.5
Antivirus Version: 1.331.1878.0
Antispyware Version: 1.331.1878.0

**Comment by vtainc** [comment]
I updated currently windows defender database and now it does not block vmping :)

Seems to be, that microsoft fixed the problem :D

**Comment by vtainc** [comment]
fixed version is:

Antivirus Version: 1.331.1892.0
Antispyware Version: 1.331.1892.0

**Comment by R-Smith** [comment]
Awesome. I turned on the automatic sample submission setting for Windows defender on my build machine which will hopefully stop false positives in the future. I previously had the setting disabled due to another project I work on.
