### ISSUE TITLE
Log Output settings not persistent

### ISSUE THREAD

**Issue by craigo-** [R-Smith/vmPing#59]
Not sure if this is intended...

When you specify Log Output settings in Options, they do not persist after closing and reopening the application.

Steps to Reproduce:

1. Options -> Log Output -> Specify a location for either or both settings -> OK
2. Verify logging is working
3. Close vmPing
4. Launch vmPing
5. Inspect Options -> Log Output: the previous settings are not retained

I inspected vmPing.xml, but do not see any log output configuration written there (even after triggering a save by adding e.g. a new favourite set).

vmPing 1.3.14, Windows 10 Enterprise 20H2

[EDIT] OK, I see that ticking "Save as vmPing defaults" results in the settings being saved to the xml and the options persisting. So I guess this is indeed the intended behaviour..?

**Comment by An-dir** [comment]
Hi craigo, 
you are right. Did you notice that no "options" settings is permanent if you don't tell them to be so?
Besides favorite sets and aliases nothing is permanent in default. non permanent favorite or alias settings would be nonsense to me, so i guess everything is almost fine as it is now. Because of the fact that it is a portable application, i agree with the current configuration that it does not store any option in default if you don't tell it to do so.

**Comment by craigo-** [comment]
Yep, the app is working as intended. All good. Just had to recalibrate my expectations.
