### ISSUE TITLE
Issue with favorites

### ISSUE THREAD

**Issue by Meganono** [R-Smith/vmPing#6]
Hi,

OS : Windows 10 1709.
OS language : FR.
C:\Windows\Microsoft.NET\Framework\v4.0.30319
C:\Windows\Microsoft.NET\Framework64\v4.0.30319
Account not admin on the PC, but running vmping with admin right does not solve the problem.

Favorites are not working.
I can add and manage favorites but when selecting one, it reset the GUI with just one grey square.

BTW, that would be a nice feature to ping a favorite with a right click on a selected square instead of having to select it from menu.

Thanks

**Comment by R-Smith** [comment]
Could you post the contents of your favorites file?  It's stored in a .xml document located at %LocalAppData%\vmPing\vmPingFavorites.xml
Edit out any information you don't want posted.  Thanks.

**Comment by Meganono** [comment]
I don't have many favorites because i always had some bugs.

Once i added 2 favorites something like :

www.google.com and then www.yahoo.com.
And when selecting 2nd fav (yahoo), it was pinging google.
But it was on another computer. On that other computer i also had a bug, i wanted to ping 8.8.8.8 and it said can't resolve.

xml content : 

```
<favorites>
  <favorite title="192.168.10.5" columncount="1">
    <host>
    </host>
  </favorite>
</favorites>
```

When i launch vmping and want to use a fav, it's like this :
![capture1](https://user-images.githubusercontent.com/35801371/35610606-371d9adc-0662-11e8-8902-c2b9a140a0c0.PNG)

Then i click on my fav and it does that :

![capture2](https://user-images.githubusercontent.com/35801371/35610648-61c43084-0662-11e8-906f-a0d94f2ab069.PNG)

Thanks.

**Comment by R-Smith** [comment]
I'll see if I can revise the interface to make "favorites" more clear.

When you select 'Favorites -> Add to favorites', it is not meant to add individual hosts as a favorite.  It's meant to create a 'favorite set'.  What it does is it takes all of the hostnames in your current vmPing window and adds them all into a single favorite set with a title of your choosing.  Since you have no hostnames entered into your vmPing window when you choose 'Add to favorites', you're essentially creating a favorite with no hosts in it which happens to be named 192.168.10.5.

Example usage would be to open vmPing, type in: 192.168.10.1, 192.168.20.1, and 192.168.30.1 into the hostname fields, and THEN go to 'Favorites -> Add to favorites', and enter a title of 'Routers' for example.  Then if you close and re-open vmPing, go to Favorites -> Routers, all 3 IPs should come up and immediately start pinging.

**Comment by Meganono** [comment]
OK i got it.
Doing that way, now the <host> part in the xml is no more empty, and it's working well.
Thx for your answer.

Maybe you could just add something in the help to explain how favorites works.
Or disable the "add to favorites" when vmping is empty or display a warning saying it will create an empty set.

**Comment by wndncg** [comment]
^grayed out is the best option when there is no data to save unto favorites category.

**Comment by R-Smith** [comment]
The application has been updated to make 'Favorites' more clear.  The menu item is now labeled 'Favorite Sets' and the menu item for creating a set is now labeled 'Save Current Layout to Favorites'.  When you select the Save... menu item, all hosts that will get saved into the set are now listed.  If you click the Save menu item and you haven't entered any hosts into vmPing, you'll get an error message.   Ideally, the Save menu item should be grayed out in this case, but for now, you'll get the error message.
