### ISSUE TITLE
Length Character on Status history

### ISSUE THREAD

**Issue by racoencmderror** [R-Smith/vmPing#67]
please add the character length in the history status or reduce the font size
![status-history](https://user-images.githubusercontent.com/86336192/123029788-e1071a80-d40b-11eb-9847-1645f3d7d653.png)

**Comment by R-Smith** [comment]
Version 1.3.16 has a new Status History window with a proper grid layout and resizable columns. But the issue still exists in the tray popup notification. This should be fixed in the next release. If the contents are too wide, it will probably be corrected in this order: reduce font size, auto stretch the width of the popup, and then horizontal scrollbars if still not wide enough.

**Comment by R-Smith** [comment]
Fixed here 67a21f781646537d0746aabcec212be86c9f7efb

Available in release 1.3.18
