### ISSUE TITLE
Memory clock of graphics card reach maximum frequency after vmPing start

### ISSUE THREAD

**Issue by akw5454521** [R-Smith/vmPing#78]
Win7  Ryzen 2600  GTX1070  .Net 4.62

The memory clock is usually 400 when there is no program running. After vmPing start (no ping start yet), the memory clock goes to 4000 immediately, and the fan of graphics card starts to work, and I can feel some lagging of the system. There is no other program running in the background.
I tried 1.3.18 to 1.3.12 and they all have the same problem. May I know how to avoid this?

**Comment by vtainc** [comment]
Yes. I also noticed, that when I'm using vmping the fan starts to work all the time ( I'm using a laptop ).

**Comment by R-Smith** [comment]
I'll look into this soon.  @vtainc are you also on Win7?

Can you try version 1.2.15 or earlier and see if it's any different?

**Comment by vtainc** [comment]
No, I was on win10, now on win11:)

**Comment by akw5454521** [comment]
> I'll look into this soon. @vtainc are you also on Win7?
> 
> Can you try version 1.2.15 or earlier and see if it's any different?

I tried 1.2.15 and 1.2.8, and the performance was the same. Now I use performance settings in Graphics card's control panel and set vmping.exe to “optimal power” and turn off every other special effects, and the situation improve a lot. Though I think it shouldn't happen in original settings

**Comment by vtainc** [comment]
HI, i will write this post here, because it is related to cpu/graphics usage.

Same behavior on: clean win10 21H2, clean win11 21H2 with latest updates and graphics drivers.
Laptop: Lenovo Thinkbook 13s gen2 intel 1165G7/16Gb and iris xe graphics.

1. GPU usage of the vmping is too high, when I try to ping many hosts this produces too high fan noise, I understand, that maybe this is normal, but other software doesn''t use gpu resources in such manner. 
2. The gpu usage has been increased after 1.3.12 by 2x...

![image](https://user-images.githubusercontent.com/19706430/162379229-cbffd384-1a30-4286-a41c-c829997debd7.png)

**Comment by R-Smith** [comment]
Can you try release 1.3.23. I disabled GPU acceleration for the app entirely.

**Comment by vtainc** [comment]
Hello.

Thank you. Now it is much better.

![image](https://user-images.githubusercontent.com/19706430/163321885-c8867fe4-f180-4f01-8b4a-fc6377178f08.png)

**Comment by R-Smith** [comment]
Glad the GPU issue is fixed! I'm going to close this issue. I've seen that problem with the blank output and I have an idea of what's causing it. I'll open a new issue for that.
