### ISSUE TITLE
您好，请问是否在未来版本支持本地化翻译，UDP 端口测试，WinMTR 持续跟踪呢？

### ISSUE THREAD

**Issue by A1472** [R-Smith/vmPing#80]
Hi R-Smith, my English is not good, your vmPing software is great 👍👍👍

I hope that in future versions
a. Support GUI localization translation function, such as nirsoft software ini file mode
b. UDP port test, such as U/\<IP address or host name\>:\<UDP port number\>
c, T/\<IP address or host name\> function, whether the function can get similar to WinMTR Net v0.92 software continuous route tracking it

**Comment by rayshen3** [comment]
牛逼啊，兄弟

**Comment by R-Smith** [comment]
Thank you!

- Localization is already open on issue #17. No progress on this. However the method Nirsoft uses with a .ini file looks very interesting. I will take a look at this again. Thanks for the suggestion!
- I don't plan on implementing a UDP port test. TCP is easy to test because it is connection-oriented. However, UDP is connection-less making any kind of detection inconsistent and unreliable.
- MTR is open on issue #12. No progress on this.

**Comment by A1472** [comment]
a. A Simplified Chinese translation was once sent to you via https://gitter.im/R-Smith on December 25, 2018, but there is a delay in adding or supporting the translation feature
b、UDP test can be done, just the operation is not as convenient as that of TCP. Suggest to refer to https://github.com/Xusser/udpping and other example code
c, WinMTR continuous route tracking, you can refer to their once popular project case code: https://sourceforge.net/projects/winmtr/, his defect is not updated for a long time, does not support IPv6. But his WinMTR software is very useful so far
